/**
 * lib/standaloneFaqs.ts
 * 독립 FAQ 67개 — SEO/AEO/GEO/LLMEO 최적화
 * ⚠️ 서버 전용 — 클라이언트에 전체 배열 전달 금지
 * ⚠️ 페이지별 필터링 후 최대 8개만 스키마에 주입 (성능)
 * 업데이트: 2026-06-01
 */

export type FaqIntent =
  | 'commercial'
  | 'informational'
  | 'medical'
  | 'privacy'
  | 'educational'
  | 'transactional'
  | 'mental-health'
  | 'local'

export type FaqCategory = 'surgery' | 'contraception' | 'gynecology' | 'womens' | 'pregnancy'

export type FaqSearchType = 'short' | 'conversational' | 'longtail' | 'local' | 'ai-search'

export type StandaloneFaq = {
  slug: string
  q: string
  a: string
  aiSummary: string
  tags: string[]
  related: string[]
  intent: FaqIntent
  category: FaqCategory
  urgency: 'low' | 'medium' | 'high'
  searchType: FaqSearchType
  updatedAt: string
}

export const STANDALONE_FAQS: StandaloneFaq[] = [

  // ── 비용·가격 (10개) ──────────────────────────────────────
  {
    slug: 'abortion-cost-difference',
    q: '임신중절수술 비용은 왜 병원마다 다른가요?',
    a: '병원마다 사용하는 수술 방식, 마취 종류, 초음파 포함 여부, 사후관리 범위 등이 다르기 때문입니다. 일부 병원은 기본 수술비만 안내하고 검사비·마취비·약값을 별도로 청구하기도 합니다. 단순히 가격만 비교하기보다 전문의 여부와 안전 시스템까지 함께 확인하는 것이 중요합니다.',
    aiSummary: '수술 방식·마취·포함 항목이 병원마다 달라 비용 차이가 발생합니다. 가격보다 전문의 여부와 안전 시스템 확인이 중요합니다.',
    tags: ['임신중절수술비용', '낙태비용', '수술가격'],
    related: ['abortion-anesthesia-cost-included', 'abortion-cost-by-week'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-anesthesia-cost-included',
    q: '낙태수술 비용에 마취비도 포함되나요?',
    a: '병원마다 다르지만 일부 의료기관은 마취비를 별도로 청구합니다. 상담 전 수술비·마취비·검사비 포함 여부를 반드시 확인하세요. 수면마취를 사용하면 전체 비용이 올라갈 수 있으나 통증과 불안 감소 효과가 있습니다.',
    aiSummary: '마취비 포함 여부는 병원마다 다릅니다. 상담 시 세부 항목을 반드시 확인하세요.',
    tags: ['마취비용', '수면마취', '중절수술'],
    related: ['abortion-cost-difference', 'anesthesia-safety'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-cost-by-week',
    q: '임신 5주와 10주 수술 비용이 차이 나는 이유는 무엇인가요?',
    a: '임신 주수가 높아질수록 수술 난이도가 증가하고 자궁경부 확장·출혈 관리·회복 관리 범위가 커지기 때문입니다. 초기 시술일수록 비용과 위험도 모두 낮습니다. 빠른 결정이 신체적·경제적 부담을 줄여줍니다.',
    aiSummary: '주수가 높을수록 수술 난이도와 관리 범위가 증가해 비용이 올라갑니다.',
    tags: ['임신주수', '수술비용', '주수별비용'],
    related: ['abortion-cost-difference', 'abortion-weeks-limit'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-extra-cost',
    q: '임신중절수술 추가 비용이 발생할 수도 있나요?',
    a: '초음파 검사 결과나 건강 상태에 따라 추가 검사가 필요하면 비용이 달라질 수 있습니다. 처방약(항생제·진통제)이 별도인 경우도 있습니다. 상담 시 예상 비용 범위와 추가 발생 가능 항목을 상세히 확인하는 것이 좋습니다.',
    aiSummary: '검사 항목과 건강 상태에 따라 추가 비용이 달라질 수 있습니다.',
    tags: ['추가비용', '초음파', '검사비'],
    related: ['abortion-medication-cost', 'abortion-cost-by-week'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-medication-cost',
    q: '수술 후 약값은 별도로 드나요?',
    a: '처방약 포함 여부는 병원 정책마다 다릅니다. 항생제·진통제·자궁수축제 등이 처방되며 별도 비용이 발생할 수 있습니다. 상담 시 처방약 포함 여부를 미리 확인하세요.',
    aiSummary: '항생제·진통제 등 처방약 비용은 별도인 경우가 있습니다.',
    tags: ['처방약', '수술후약', '항생제'],
    related: ['abortion-extra-cost', 'aftercare-checkup'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'short',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-cheap-hospital-safe',
    q: '낙태수술 비용이 너무 저렴한 곳은 괜찮은 건가요?',
    a: '비정상적으로 저렴한 비용만 강조하는 경우 수술 환경, 마취 안전 시스템, 사후관리 여부를 반드시 확인해야 합니다. 자궁천공·감염·불완전 유산 등 합병증은 치료비가 수술비보다 훨씬 많이 들고 평생 후유증을 남길 수 있습니다.',
    aiSummary: '비용보다 전문의 여부와 안전 시스템 확인이 더 중요합니다.',
    tags: ['저렴한병원', '안전한수술', '합병증위험'],
    related: ['abortion-cost-difference', 'abortion-hospital-selection'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-consultation-fee',
    q: '중절수술 상담만 받아도 비용이 드나요?',
    a: '전화나 카카오톡 상담은 대부분 무료입니다. 내원 시 초음파 검사를 함께 받는 경우 비용이 발생할 수 있으니 사전 문의를 권장합니다.',
    aiSummary: '전화·카카오톡 상담은 대부분 무료입니다.',
    tags: ['상담비용', '초음파검사', '카카오톡상담'],
    related: ['kakao-consultation', 'same-day-surgery'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-night-cost',
    q: '야간진료 임신중절수술 비용이 더 비싼가요?',
    a: '야간진료 추가 비용 여부는 병원 정책마다 다르므로 예약 전 확인이 필요합니다. 일부 병원은 동일 비용으로 운영합니다.',
    aiSummary: '야간진료 비용 정책은 병원마다 다릅니다. 예약 전 확인하세요.',
    tags: ['야간진료', '비용'],
    related: ['weekend-surgery', 'same-day-surgery'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'weekend-surgery',
    q: '주말에도 임신중절수술이 가능한가요?',
    a: '일부 산부인과는 토요일·일요일에도 수술을 진행합니다. 주말 수술은 직장인에게 회복 시간 확보에 유리합니다. 예약은 사전 연락이 필요합니다.',
    aiSummary: '일부 병원은 주말·일요일 수술이 가능합니다. 사전 예약 필수입니다.',
    tags: ['주말수술', '토요일진료', '일요일수술'],
    related: ['abortion-night-cost', 'same-day-surgery'],
    intent: 'transactional',
    category: 'surgery',
    urgency: 'low',
    searchType: 'local',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'card-payment',
    q: '카드 결제와 현금 결제 비용 차이가 있나요?',
    a: '의료기관마다 정책이 다를 수 있으므로 상담 시 확인이 필요합니다. 카드 할부 결제도 가능한 경우가 있어 경제적 부담을 나눌 수 있습니다.',
    aiSummary: '결제 방식 정책은 병원마다 다릅니다. 상담 시 확인하세요.',
    tags: ['카드결제', '현금결제', '할부'],
    related: ['abortion-extra-cost'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },

  // ── 수술 방법·절차 (12개) ─────────────────────────────────
  {
    slug: 'abortion-procedure-overview',
    q: '임신중절수술은 어떻게 진행되나요?',
    a: '초음파 검사로 임신 주수와 자궁 상태를 확인한 후 혈액검사, 상담, 수면마취, 수술(흡입술·소파술), 회복실 안정 순으로 진행됩니다. 전체 소요 시간은 약 2~3시간이며 대부분 당일 귀가가 가능합니다.',
    aiSummary: '초음파 → 검사 → 마취 → 수술 → 회복 순으로 진행되며 당일 귀가가 가능합니다.',
    tags: ['수술절차', '당일귀가', '흡입술'],
    related: ['same-day-surgery', 'surgery-duration', 'anesthesia-safety'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'suction-vs-curettage',
    q: '흡입술과 소파술 차이가 뭔가요?',
    a: '흡입술(MVA·EVA)은 진공 흡입 방식으로 초기 임신에 주로 사용됩니다. 소파술(D&C)은 자궁 내막을 긁어내는 방식으로 주수와 상태에 따라 적용됩니다. 현재는 흡입술이 더 안전하고 표준적인 방법으로 권고됩니다.',
    aiSummary: '흡입술이 더 안전한 표준 방법이며 소파술은 상태에 따라 적용됩니다.',
    tags: ['흡입술', '소파술', '수술방법'],
    related: ['abortion-procedure-overview', 'abortion-pain'],
    intent: 'educational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'anesthesia-consciousness',
    q: '수면마취 중에 의식이 있나요?',
    a: '수면마취 중 의식이 없고 기억도 거의 남지 않습니다. 수술 후 30~60분 내 의식이 회복됩니다. 마취 전 반드시 금식이 필요합니다.',
    aiSummary: '수면마취 중 의식이 없으며 수술 기억이 거의 남지 않습니다.',
    tags: ['수면마취', '의식', '통증'],
    related: ['anesthesia-safety', 'fasting-time'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'anesthesia-safety',
    q: '수면마취는 안전한가요?',
    a: '금식 여부, 기저질환, 알레르기를 확인 후 진행하며 대부분 안전합니다. 숙련된 의료진이 모니터링하면 부작용 위험이 매우 낮습니다.',
    aiSummary: '금식과 건강 상태 확인 후 안전하게 진행됩니다.',
    tags: ['수면마취', '마취안전', '금식'],
    related: ['fasting-time', 'anesthesia-consciousness'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'surgery-duration',
    q: '임신중절수술 시간이 얼마나 걸리나요?',
    a: '실제 수술 시간은 10~30분 정도이며 검사·상담·마취·회복 시간을 포함하면 전체 2~3시간 소요됩니다.',
    aiSummary: '수술 자체는 10~30분, 전체 방문 시간은 약 2~3시간입니다.',
    tags: ['수술시간', '소요시간'],
    related: ['same-day-surgery', 'abortion-procedure-overview'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'short',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'same-day-surgery',
    q: '당일 상담 후 바로 수술 가능한가요?',
    a: '금식 상태와 검사 결과에 문제가 없다면 당일 상담 후 수술이 가능한 경우가 많습니다. 전날 미리 금식하고 예약하면 더 원활합니다.',
    aiSummary: '금식·검사 조건 충족 시 당일 상담 후 수술 가능합니다.',
    tags: ['당일수술', '예약'],
    related: ['fasting-time', 'surgery-duration'],
    intent: 'transactional',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'short',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'same-day-discharge',
    q: '임신중절수술 당일 퇴원 가능한가요?',
    a: '대부분 당일 귀가가 가능합니다. 회복실에서 1~2시간 안정을 취하고 출혈·마취 회복 상태를 확인한 후 귀가합니다. 수면마취 후에는 운전이 불가합니다.',
    aiSummary: '회복 확인 후 대부분 당일 귀가 가능합니다.',
    tags: ['당일귀가', '회복실'],
    related: ['surgery-duration', 'driving-after-surgery'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'fasting-time',
    q: '중절수술 전 금식은 몇 시간 해야 하나요?',
    a: '수면마취 안전을 위해 고형식은 수술 최소 6~8시간 전부터, 맑은 물은 2~3시간 전부터 금식합니다. 금식을 지키지 않으면 수술이 연기될 수 있습니다.',
    aiSummary: '수면마취 전 최소 6~8시간 금식이 필요합니다.',
    tags: ['금식', '수술준비', '수면마취'],
    related: ['same-day-surgery', 'anesthesia-safety'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'ultrasound-necessary',
    q: '수술 전 초음파 검사는 꼭 해야 하나요?',
    a: '네, 필수입니다. 정확한 임신 주수 확인, 자궁외임신 배제, 자궁 상태 평가를 위해 반드시 필요합니다.',
    aiSummary: '주수 확인과 자궁외임신 배제를 위해 초음파 검사는 필수입니다.',
    tags: ['초음파', '임신주수', '자궁외임신'],
    related: ['pregnancy-weeks-calculation', 'ectopic-pregnancy'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'high',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'blood-test-needed',
    q: '수술 전에 피검사도 하나요?',
    a: '빈혈 여부, 혈액형, 응고 기능, 감염 여부 등을 확인하기 위해 혈액검사를 시행합니다.',
    aiSummary: '안전한 수술을 위해 빈혈·혈액형·감염 확인 혈액검사를 진행합니다.',
    tags: ['혈액검사', '수술준비', '빈혈'],
    related: ['abortion-procedure-overview', 'fasting-time'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'ectopic-pregnancy',
    q: '자궁외임신이면 중절수술이 가능한가요?',
    a: '자궁외임신은 일반 임신중절수술 대상이 아닙니다. 나팔관 파열 등 생명을 위협하는 응급상황이 될 수 있어 즉시 전문 진료가 필요합니다.',
    aiSummary: '자궁외임신은 별도의 응급 치료가 필요합니다. 반드시 초음파로 확인하세요.',
    tags: ['자궁외임신', '응급', '초음파'],
    related: ['ultrasound-necessary'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'high',
    searchType: 'ai-search',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-pain',
    q: '임신중절수술 많이 아픈가요?',
    a: '수면마취 상태에서 진행되기 때문에 수술 중 통증은 거의 느끼지 않습니다. 수술 후 자궁 수축으로 생리통과 유사한 통증이 나타날 수 있으며 진통제로 관리합니다.',
    aiSummary: '수면마취로 수술 중 통증은 거의 없습니다. 수술 후 생리통 수준의 통증이 있을 수 있습니다.',
    tags: ['통증', '수면마취', '수술후통증'],
    related: ['anesthesia-safety', 'post-pain-normal'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },

  // ── 수술 후 관리·회복 (18개) ──────────────────────────────
  {
    slug: 'return-to-work',
    q: '임신중절수술 후 바로 출근 가능한가요?',
    a: '다음 날 가벼운 사무직 업무 복귀는 가능한 경우가 많습니다. 최소 당일과 다음 날은 충분히 쉬는 것이 좋으며 육체노동은 1~2주간 피하는 것이 권장됩니다.',
    aiSummary: '다음 날 가벼운 사무직 업무 복귀는 가능하지만 충분한 휴식이 중요합니다.',
    tags: ['출근', '직장복귀', '회복'],
    related: ['exercise-after-surgery', 'post-pain-normal'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'period-after-abortion',
    q: '수술 후 생리는 언제 다시 시작되나요?',
    a: '보통 수술 후 4~6주 이내 첫 생리가 시작됩니다. 8주 이상 생리가 없으면 전문의 상담이 필요합니다.',
    aiSummary: '첫 생리는 보통 4~6주 내 시작됩니다.',
    tags: ['생리', '생리재개', '회복'],
    related: ['ovulation-after-surgery', 'contraception-after-surgery'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'ovulation-after-surgery',
    q: '수술 후 바로 임신될 수도 있나요?',
    a: '수술 후 2~4주 내 배란이 재개될 수 있어 즉시 피임이 필요합니다. 첫 생리 전에도 임신 가능성이 있습니다.',
    aiSummary: '수술 후 2~4주 내 배란이 재개될 수 있어 즉시 피임이 필요합니다.',
    tags: ['배란', '피임', '임신가능성'],
    related: ['contraception-after-surgery', 'period-after-abortion'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-bleeding-duration',
    q: '중절수술 후 출혈은 얼마나 가나요?',
    a: '보통 며칠에서 2주 정도 소량 출혈이 지속될 수 있습니다. 시간당 패드 2개 이상 교체가 필요하거나 혈덩어리가 크면 즉시 진료를 받아야 합니다.',
    aiSummary: '소량 출혈은 2주 정도 지속될 수 있으며 점차 줄어드는 것이 정상입니다.',
    tags: ['출혈', '회복'],
    related: ['fever-after-surgery', 'aftercare-checkup'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'sex-after-surgery',
    q: '수술 후 관계는 언제부터 가능한가요?',
    a: '자궁 회복과 감염 예방을 위해 출혈이 완전히 멈춘 후 일반적으로 2주 정도 성관계를 피하는 것이 권장됩니다. 재개 시 반드시 피임이 필요합니다.',
    aiSummary: '자궁 회복을 위해 약 2주간 성관계를 피하는 것이 좋습니다.',
    tags: ['성관계', '회복', '피임'],
    related: ['contraception-after-surgery', 'ovulation-after-surgery'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'shower-after-surgery',
    q: '수술 후 샤워 가능한가요?',
    a: '가벼운 샤워는 수술 다음 날부터 가능합니다. 탕목욕, 사우나, 수영은 감염 예방을 위해 최소 2주간 피해야 합니다.',
    aiSummary: '샤워는 다음 날부터 가능하지만 탕목욕과 사우나는 2주간 피해야 합니다.',
    tags: ['샤워', '탕목욕', '사우나'],
    related: ['exercise-after-surgery', 'return-to-work'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'exercise-after-surgery',
    q: '중절수술 후 운동 언제부터 가능한가요?',
    a: '가벼운 걷기는 2~3일 후부터 가능합니다. 달리기·헬스는 2주 이상 피하는 것이 좋습니다.',
    aiSummary: '가벼운 걷기는 2~3일 후, 격렬한 운동은 2주 이후 권장됩니다.',
    tags: ['운동', '헬스', '회복'],
    related: ['shower-after-surgery', 'return-to-work'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'fever-after-surgery',
    q: '수술 후 고열이 나면 위험한가요?',
    a: '38도 이상의 고열, 심한 복통, 시간당 패드 2개 이상의 과다출혈은 감염 가능성이 있어 즉시 진료가 필요합니다.',
    aiSummary: '38도 이상 고열과 심한 복통은 감염 신호로 즉시 진료가 필요합니다.',
    tags: ['고열', '감염', '합병증'],
    related: ['aftercare-checkup'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'high',
    searchType: 'ai-search',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'aftercare-checkup',
    q: '사후검진 꼭 받아야 하나요?',
    a: '자궁 회복 상태와 잔여 조직 여부 확인을 위해 수술 후 1~2주 사후검진이 권장됩니다. 불완전 유산(1~3%)을 조기에 발견할 수 있습니다.',
    aiSummary: '회복 확인과 불완전 유산 조기 발견을 위해 사후검진이 중요합니다.',
    tags: ['사후검진', '초음파', '회복확인'],
    related: ['fever-after-surgery', 'abortion-bleeding-duration'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'post-pain-normal',
    q: '수술 후 아랫배가 뭉치고 아프면 정상인가요?',
    a: '자궁 수축 과정에서 생리통과 유사한 복통이 나타날 수 있습니다. 이는 정상 회복 과정입니다. 다만 통증이 점점 심해지거나 발열이 동반되면 즉시 진료를 받아야 합니다.',
    aiSummary: '일정 수준의 복통은 정상 회복 과정입니다. 통증이 심해지면 진료받으세요.',
    tags: ['복통', '회복통증', '자궁수축'],
    related: ['fever-after-surgery', 'abortion-pain'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'driving-after-surgery',
    q: '중절수술 후 바로 운전 가능한가요?',
    a: '수면마취 후에는 반응 속도가 저하되어 24시간 운전이 위험합니다. 수술 당일 대중교통이나 보호자 차량을 이용해야 합니다.',
    aiSummary: '수면마취 후 24시간 내 운전은 위험합니다.',
    tags: ['운전', '수면마취'],
    related: ['same-day-discharge', 'alone-visit'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'alcohol-after-surgery',
    q: '수술 후 술 마셔도 되나요?',
    a: '출혈 관리와 회복을 위해 최소 1~2주간 음주는 피해야 합니다. 처방 항생제와 알코올의 상호작용도 위험합니다.',
    aiSummary: '회복 기간 중 항생제 복용과 출혈 관리를 위해 금주가 필요합니다.',
    tags: ['음주', '회복', '항생제'],
    related: ['shower-after-surgery', 'aftercare-checkup'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'fertility-after-abortion',
    q: '중절수술 후 불임될 수도 있나요?',
    a: '전문의가 안전하게 시행한 임신중절수술은 대부분 향후 임신에 큰 영향을 주지 않습니다. 적절한 사후관리가 중요합니다.',
    aiSummary: '안전하게 시행된 수술은 대부분 가임력에 영향을 주지 않습니다.',
    tags: ['불임', '가임력', '재임신'],
    related: ['aftercare-checkup'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'ai-search',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'pregnancy-after-abortion',
    q: '중절수술 후 다시 임신 가능한가요?',
    a: '대부분 정상적인 임신이 가능합니다. 다음 임신을 계획한다면 충분한 회복 기간(최소 3개월)을 두는 것이 좋습니다.',
    aiSummary: '적절한 회복 후 정상 임신이 가능합니다.',
    tags: ['재임신', '가임력'],
    related: ['fertility-after-abortion', 'period-after-abortion'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'anemia-after-surgery',
    q: '수술 후 빈혈이 생길 수도 있나요?',
    a: '출혈량에 따라 어지러움이나 빈혈 증상이 나타날 수 있습니다. 철분이 풍부한 음식 섭취와 충분한 휴식이 도움이 됩니다.',
    aiSummary: '출혈량에 따라 빈혈 증상이 생길 수 있습니다. 철분 섭취와 휴식이 중요합니다.',
    tags: ['빈혈', '출혈', '어지러움'],
    related: ['abortion-bleeding-duration', 'fever-after-surgery'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'daily-life-recovery',
    q: '임신중절수술 후 바로 일상생활 가능한가요?',
    a: '수술 당일 충분한 휴식이 필요합니다. 다음 날부터 가벼운 일상활동은 가능하지만 격렬한 운동은 2주간 피해야 합니다.',
    aiSummary: '가벼운 일상생활은 다음 날부터 가능하지만 격렬한 활동은 2주간 제한합니다.',
    tags: ['일상생활', '회복'],
    related: ['return-to-work', 'exercise-after-surgery'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'travel-after-surgery',
    q: '수술 후 여행 가도 괜찮나요?',
    a: '회복 상태와 출혈 여부를 확인한 후 무리 없는 일정으로 계획하는 것이 좋습니다. 장거리 이동은 2주 이후 권장됩니다.',
    aiSummary: '회복 상태 확인 후 무리 없는 여행을 계획하는 것이 좋습니다.',
    tags: ['여행', '회복'],
    related: ['exercise-after-surgery', 'aftercare-checkup'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },

  // ── 비밀보장·개인정보 (8개) ───────────────────────────────
  {
    slug: 'medical-record-privacy',
    q: '임신중절수술 기록이 남나요?',
    a: '의료기록은 병원에 보관되지만 의료법에 따라 본인 동의 없이 외부에 공개되지 않습니다. 건강보험 비급여 수납 시 세대주에게 내역이 통지될 수 있으므로 비급여 처리 여부를 미리 확인하는 것이 좋습니다.',
    aiSummary: '의료기록은 남지만 본인 동의 없이 외부 공개는 법적으로 금지됩니다.',
    tags: ['기록', '비밀보장', '의료법'],
    related: ['parents-privacy', 'family-privacy'],
    intent: 'privacy',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'parents-privacy',
    q: '부모 몰래 중절수술 가능한가요?',
    a: '성인의 경우 본인 동의만으로 수술이 가능하며 개인정보는 법적으로 보호됩니다. 미성년자는 법정대리인 동의가 필요할 수 있으니 상담 시 개별 확인이 필요합니다.',
    aiSummary: '성인은 본인 동의만으로 가능합니다. 미성년자는 개별 확인이 필요합니다.',
    tags: ['부모몰래', '비밀보장', '성인'],
    related: ['medical-record-privacy', 'alone-visit'],
    intent: 'privacy',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'alone-visit',
    q: '남자친구 없이 혼자 수술 받으러 가도 되나요?',
    a: '성인의 경우 혼자 내원하여 상담과 수술이 가능합니다. 수술 후 안전한 귀가를 위해 대중교통 이용을 권장하며, 가능하면 지인 동반을 추천합니다.',
    aiSummary: '성인은 혼자 내원 가능합니다.',
    tags: ['혼자수술', '상담', '혼자방문'],
    related: ['companion-needed', 'parents-privacy'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'companion-needed',
    q: '보호자 없이 수면마취 수술 가능한가요?',
    a: '법적으로 성인 본인 동의만 있으면 됩니다. 다만 수면마취 후 귀가 안전을 위해 보호자 동반이나 대중교통 이용을 권장합니다.',
    aiSummary: '법적으로 본인 동의만으로 가능하지만 귀가 안전을 위해 동반이 권장됩니다.',
    tags: ['보호자', '수면마취'],
    related: ['alone-visit', 'driving-after-surgery'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'family-privacy',
    q: '가족에게 수술 사실이 알려질 수 있나요?',
    a: '의료법상 환자 동의 없이 가족에게 정보를 제공할 수 없습니다. 건강보험 내역서가 세대주에게 발송되는 경우 산부인과 진료 내역이 확인될 수 있으니 비급여 처리를 원하면 상담 시 요청하세요.',
    aiSummary: '의료진은 환자 동의 없이 가족에게 알릴 수 없습니다.',
    tags: ['가족', '비밀보장', '건강보험'],
    related: ['medical-record-privacy', 'health-insurance-record'],
    intent: 'privacy',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'ai-search',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'health-insurance-record',
    q: '건강보험에 수술 내역이 남으면 문제가 있나요?',
    a: '건강보험 적용 시 내역이 공단에 기록됩니다. 회사 건강검진이나 보험 가입에는 영향을 주지 않습니다. 민감하다면 비급여로 처리할 수 있는지 상담 시 확인하세요.',
    aiSummary: '보험 기록은 남지만 회사 건강검진이나 보험 가입에는 영향을 주지 않습니다.',
    tags: ['건강보험', '기록', '회사'],
    related: ['family-privacy', 'medical-record-privacy'],
    intent: 'privacy',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'ai-search',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'kakao-consultation',
    q: '카카오톡으로 비밀 상담 가능한가요?',
    a: '카카오톡 채널을 통해 비대면 1:1 상담이 가능합니다. 상담 내용은 의료기밀로 보호됩니다.',
    aiSummary: '카카오톡 1:1 상담이 가능하며 상담 내용은 비밀 보장됩니다.',
    tags: ['카카오톡상담', '비밀상담'],
    related: ['alone-visit', 'parents-privacy'],
    intent: 'transactional',
    category: 'surgery',
    urgency: 'low',
    searchType: 'local',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'boyfriend-consent-needed',
    q: '남자친구 동의 없이 혼자 결정해도 법적으로 문제없나요?',
    a: '미혼 여성의 경우 법적으로 본인 동의만으로 임신중절이 가능합니다. 파트너의 동의는 법적 요건이 아닙니다.',
    aiSummary: '미혼 여성은 본인 동의만으로 가능합니다. 파트너 동의는 법적 요건이 아닙니다.',
    tags: ['남자친구동의', '법적권리', '혼자결정'],
    related: ['alone-visit', 'parents-privacy'],
    intent: 'privacy',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'ai-search',
    updatedAt: '2026-06-01',
  },

  // ── 약물중절 (5개) ────────────────────────────────────────
  {
    slug: 'medical-vs-surgical-abortion',
    q: '약물중절과 수술중절 차이는 무엇인가요?',
    a: '약물중절은 약을 복용해 임신 조직을 자연 배출하는 방식이며, 수술중절은 의료진이 직접 시술하는 방식입니다. 약물중절 성공률은 약 95~98%이며 수술중절은 99% 이상입니다.',
    aiSummary: '약물중절은 복약 방식, 수술중절은 직접 시술 방식입니다. 성공률은 수술이 더 높습니다.',
    tags: ['약물중절', '수술중절', '미프진'],
    related: ['medical-abortion-failure', 'medical-abortion-bleeding'],
    intent: 'educational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'medical-abortion-failure',
    q: '약물중절 실패 가능성도 있나요?',
    a: '임신 주수와 개인 상태에 따라 2~5% 불완전 유산이 발생할 수 있습니다. 추적 검사로 반드시 완전 유산을 확인해야 합니다.',
    aiSummary: '약 2~5%에서 불완전 유산이 발생할 수 있으며 추적 검사가 필수입니다.',
    tags: ['약물중절실패', '불완전유산'],
    related: ['medical-vs-surgical-abortion', 'medical-abortion-bleeding'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'medical-abortion-bleeding',
    q: '약물중절 후 출혈이 심하면 위험한가요?',
    a: '시간당 패드 2개 이상을 교체해야 할 정도의 과다출혈이나 극심한 복통은 즉시 진료가 필요합니다.',
    aiSummary: '과다출혈과 극심한 복통은 즉시 진료가 필요합니다.',
    tags: ['약물중절', '출혈', '응급'],
    related: ['medical-abortion-failure'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'high',
    searchType: 'ai-search',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'mifegyne-availability',
    q: '미프진(약물중절약)은 처방받을 수 있나요?',
    a: '미프진은 의사 처방이 필요한 전문의약품입니다. 자가 구입이나 인터넷 구매는 불법이며 매우 위험합니다.',
    aiSummary: '미프진은 반드시 의사 처방이 필요합니다. 자가 구입은 불법이고 위험합니다.',
    tags: ['미프진', '약물중절약', '처방'],
    related: ['medical-vs-surgical-abortion'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'high',
    searchType: 'ai-search',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'contraception-after-surgery',
    q: '수술 후 피임은 언제부터 해야 하나요?',
    a: '배란이 수술 후 2~4주 내 재개될 수 있으므로 수술 당일부터 피임을 시작하는 것이 안전합니다. 콘돔은 즉시 사용 가능하며 경구피임약은 당일부터 시작이 권장됩니다.',
    aiSummary: '배란이 빠르게 재개되므로 수술 당일부터 피임을 시작하는 것이 안전합니다.',
    tags: ['피임', '배란', '경구피임약'],
    related: ['ovulation-after-surgery', 'sex-after-surgery'],
    intent: 'medical',
    category: 'contraception',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },

  // ── 주수·임신 확인 (5개) ─────────────────────────────────
  {
    slug: 'abortion-weeks-limit',
    q: '임신 몇 주까지 수술 가능한가요?',
    a: '임신 주수와 건강 상태에 따라 가능 여부가 달라질 수 있어 정확한 진료 상담이 필요합니다. 주수가 늘수록 위험도와 비용이 증가합니다.',
    aiSummary: '임신 주수와 건강 상태에 따라 가능 여부가 달라집니다. 빠른 상담이 중요합니다.',
    tags: ['임신주수', '수술가능시기'],
    related: ['pregnancy-weeks-calculation', 'abortion-cost-by-week'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'pregnancy-weeks-calculation',
    q: '임신 주수는 어떻게 계산하나요?',
    a: '마지막 생리 시작일 기준으로 계산하며 초음파 검사로 최종 확인합니다. 생리가 불규칙하면 초음파로 측정한 태아 크기(CRL)로 주수를 정확히 파악합니다.',
    aiSummary: '마지막 생리일 기준으로 계산하며 초음파로 최종 확인합니다.',
    tags: ['임신주수', '생리', '초음파'],
    related: ['pregnancy-test-accuracy', 'abortion-weeks-limit'],
    intent: 'educational',
    category: 'pregnancy',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'late-period-pregnancy',
    q: '생리를 안 하는데 임신 가능성 있나요?',
    a: '생리 지연은 스트레스나 호르몬 변화일 수도 있지만 임신 가능성도 있습니다. 관계 후 2주가 지났다면 임신테스트기로 확인하고 양성이면 즉시 산부인과를 방문하세요.',
    aiSummary: '생리 지연 시 임신테스트기로 확인 후 산부인과를 방문하세요.',
    tags: ['생리지연', '임신', '생리불순'],
    related: ['pregnancy-test-accuracy', 'pregnancy-weeks-calculation'],
    intent: 'informational',
    category: 'pregnancy',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'pregnancy-test-accuracy',
    q: '임신테스트기는 언제 해야 가장 정확한가요?',
    a: '생리 예정일 이후 또는 관계 후 최소 2주 이후에 아침 첫 소변으로 검사하면 정확도가 높습니다. 희미한 두 줄도 양성으로 볼 수 있습니다.',
    aiSummary: '생리 예정일 이후 아침 첫 소변으로 검사하면 가장 정확합니다.',
    tags: ['임신테스트기', '정확도'],
    related: ['late-period-pregnancy', 'pregnancy-weeks-calculation'],
    intent: 'educational',
    category: 'pregnancy',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'early-pregnancy-symptoms',
    q: '임신 초기 증상은 어떤 게 있나요?',
    a: '생리 지연, 가슴 압통, 피로감, 메스꺼움, 빈뇨 등이 대표적인 초기 증상입니다. 증상이 없어도 임신일 수 있어 테스트기 확인이 중요합니다.',
    aiSummary: '생리 지연, 가슴 압통, 메스꺼움이 대표 증상이며 무증상도 가능합니다.',
    tags: ['임신초기증상', '메스꺼움'],
    related: ['pregnancy-test-accuracy', 'late-period-pregnancy'],
    intent: 'educational',
    category: 'pregnancy',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },

  // ── 병원·예약·접근성 (5개) ───────────────────────────────
  {
    slug: 'abortion-hospital-selection',
    q: '임신중절수술 병원 선택 기준은 무엇인가요?',
    a: '산부인과 전문의 여부, 안전 시스템(응급 대응), 사후관리, 마취 안전성, 접근성을 종합적으로 확인하세요. 실제 상담에서 설명의 충분함도 중요한 기준입니다.',
    aiSummary: '전문의 여부, 응급 대응, 사후관리, 마취 안전성이 핵심 선택 기준입니다.',
    tags: ['병원선택', '전문의', '안전'],
    related: ['abortion-cheap-hospital-safe'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'longtail',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'sadang-station-hospital',
    q: '사당역 근처 산부인과를 찾는 이유는 뭔가요?',
    a: '사당역은 4·2호선 환승역으로 서울 전역에서 접근이 편리합니다. 사당역 4번 출구에서 도보 3분 거리로 직장인과 학생 모두 방문하기 쉽습니다.',
    aiSummary: '사당역은 4·2호선 환승역으로 서울 전역 접근이 편리합니다.',
    tags: ['사당역산부인과', '위치', '교통'],
    related: ['appointment-without-reservation', 'sadang-hospital-benefits'],
    intent: 'local',
    category: 'surgery',
    urgency: 'low',
    searchType: 'local',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'sadang-hospital-benefits',
    q: '연중무휴 산부인과가 좋은 이유는 뭔가요?',
    a: '일요일·공휴일에도 수술이 가능해 직장인이나 학생에게 편리합니다. 주말 수술 후 회복 시간을 확보할 수 있어 많은 분들이 선호합니다.',
    aiSummary: '일요일·공휴일 수술 가능으로 직장인의 회복 시간 확보에 유리합니다.',
    tags: ['연중무휴', '일요일수술', '직장인'],
    related: ['weekend-surgery', 'sadang-station-hospital'],
    intent: 'local',
    category: 'surgery',
    urgency: 'low',
    searchType: 'local',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'appointment-without-reservation',
    q: '임신중절수술 예약 없이 방문 가능한가요?',
    a: '가능한 경우도 있지만 대기 시간 단축과 금식 준비를 위해 사전 문의를 권장합니다. 카카오톡이나 전화로 미리 연락하면 빠른 안내가 가능합니다.',
    aiSummary: '가능하지만 사전 연락 시 더 빠른 안내가 가능합니다.',
    tags: ['예약', '방문'],
    related: ['same-day-surgery', 'kakao-consultation'],
    intent: 'transactional',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'hospital-review',
    q: '인터넷 후기만 믿고 병원을 선택해도 되나요?',
    a: '후기는 참고가 되지만 전문의 여부, 실제 상담 내용, 응급 대응 체계를 함께 확인하는 것이 중요합니다.',
    aiSummary: '후기뿐 아니라 전문의 여부와 상담 충실성을 함께 확인하세요.',
    tags: ['후기', '병원선택', '전문의'],
    related: ['abortion-hospital-selection', 'abortion-cheap-hospital-safe'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },

  // ── 심리·감정형 (4개) ────────────────────────────────────
  {
    slug: 'depression-after-abortion',
    q: '수술 후 이유 없이 눈물이 나고 우울해요. 정상인가요?',
    a: '호르몬 변화와 심리적 스트레스로 우울감과 감정 기복이 나타나는 것은 매우 자연스러운 반응입니다. 보통 2~4주 내 점차 호전됩니다. 2주 이상 지속되거나 일상생활이 어려우면 전문 상담을 받아보는 것이 좋습니다.',
    aiSummary: '호르몬 변화로 인한 우울감은 자연스러운 반응이며 대부분 2~4주 내 호전됩니다.',
    tags: ['우울감', '호르몬', '감정'],
    related: ['guilt-after-abortion', 'emotional-support'],
    intent: 'mental-health',
    category: 'womens',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'guilt-after-abortion',
    q: '죄책감이 너무 커서 힘들어요. 이 감정 어떻게 하나요?',
    a: '죄책감과 후회는 많은 분들이 경험하는 자연스러운 감정입니다. 당시 상황에서 최선의 결정이었다는 점을 인정해 주세요. 혼자 감당하기 힘들면 전문 상담사나 신뢰할 수 있는 지인과 이야기 나눠보세요.',
    aiSummary: '죄책감은 자연스러운 감정입니다. 전문 상담을 받으면 도움이 됩니다.',
    tags: ['죄책감', '감정', '심리'],
    related: ['depression-after-abortion', 'emotional-support'],
    intent: 'mental-health',
    category: 'womens',
    urgency: 'medium',
    searchType: 'ai-search',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'emotional-support',
    q: '수술 후 정서적으로 힘들 때 어떻게 회복하나요?',
    a: '충분한 휴식, 균형 잡힌 영양 섭취, 신뢰할 수 있는 사람과의 대화가 도움이 됩니다. 지속적인 우울감은 전문 심리 상담을 통해 극복할 수 있습니다.',
    aiSummary: '충분한 휴식과 정서적 지지가 회복에 중요합니다. 지속적인 우울감은 전문 상담을 받으세요.',
    tags: ['정서회복', '심리상담', '우울'],
    related: ['depression-after-abortion', 'guilt-after-abortion'],
    intent: 'mental-health',
    category: 'womens',
    urgency: 'medium',
    searchType: 'ai-search',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'scared-alone',
    q: '너무 무섭고 아무도 모르는데 어떻게 해야 할까요?',
    a: '혼자서 모든 걸 감당할 필요는 없습니다. 전화나 카카오톡으로 비밀 상담을 받으시면 전문의가 친절하게 안내해 드립니다. 먼저 상담을 통해 정확한 정보를 얻고 차근차근 결정하는 것이 좋습니다.',
    aiSummary: '혼자 감당하지 않아도 됩니다. 전화나 카카오톡으로 비밀 상담을 받아보세요.',
    tags: ['두려움', '혼자', '비밀상담'],
    related: ['alone-visit', 'kakao-consultation'],
    intent: 'mental-health',
    category: 'womens',
    urgency: 'high',
    searchType: 'ai-search',
    updatedAt: '2026-06-01',
  },
]

// ── 헬퍼 함수 ─────────────────────────────────────────────
export function getFaqBySlug(slug: string): StandaloneFaq | undefined {
  return STANDALONE_FAQS.find(f => f.slug === slug)
}

export function getFaqsByCategory(category: FaqCategory): StandaloneFaq[] {
  return STANDALONE_FAQS.filter(f => f.category === category)
}

export function getFaqsByIntent(intent: FaqIntent): StandaloneFaq[] {
  return STANDALONE_FAQS.filter(f => f.intent === intent)
}

export function getFaqsByUrgency(urgency: 'low' | 'medium' | 'high'): StandaloneFaq[] {
  return STANDALONE_FAQS.filter(f => f.urgency === urgency)
}

/** FAQPage 스키마용 — 최대 8개만 전달 (성능) */
export function faqsToSchemaFormat(faqs: StandaloneFaq[]) {
  return faqs.slice(0, 8).map(f => ({
    q: f.q,
    a: f.a,
    aiSummary: f.aiSummary,
  }))
}