import type { StandaloneFaq } from '../standaloneFaqs'

export const MINOR_FAQS: StandaloneFaq[] = [
  {
    slug: 'minor-abortion-possible',
    q: '미성년자도 임신중절수술 받을 수 있나요?',
    a: '미성년자도 임신중절수술이 가능하며 개별 상황에 따라 필요한 서류와 절차가 다를 수 있습니다. 먼저 전화나 카카오톡으로 비밀 상담을 받으시면 정확한 안내를 드릴 수 있습니다.',
    aiSummary: '미성년자도 수술이 가능하며 개별 상황에 맞는 안내를 상담으로 받을 수 있습니다.',
    tags: ['미성년자', '청소년임신', '중절수술'],
    related: ['parents-privacy', 'scared-alone'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'high',
    searchType: 'ai-search',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'minor-parents-must-know',
    q: '고등학생인데 부모님한테 꼭 알려야 하나요?',
    a: '개별 상황에 따라 다를 수 있으므로 먼저 비밀 상담을 통해 정확한 안내를 받는 것이 중요합니다. 전화나 카카오톡으로 먼저 연락 주시면 상황에 맞게 안내드립니다.',
    aiSummary: '개별 상황에 따라 다르므로 먼저 비밀 상담을 통해 정확한 안내를 받는 것이 중요합니다.',
    tags: ['고등학생', '부모동의', '미성년자'],
    related: ['minor-abortion-possible', 'parents-privacy'],
    intent: 'privacy',
    category: 'surgery',
    urgency: 'high',
    searchType: 'ai-search',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'minor-alone-visit',
    q: '미성년자 혼자 병원 가도 되나요?',
    a: '먼저 전화나 카카오톡으로 상담하시면 개별 상황에 맞는 방문 방법을 안내드립니다. 혼자 방문이 어렵거나 두렵다면 신뢰할 수 있는 지인과 함께 오셔도 됩니다.',
    aiSummary: '먼저 비밀 상담을 통해 개별 상황에 맞는 방문 방법을 안내받을 수 있습니다.',
    tags: ['미성년자혼자', '청소년방문'],
    related: ['minor-abortion-possible', 'alone-visit'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'high',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'student-work-after',
    q: '수술 다음 날 학교 가도 되나요?',
    a: '수술 당일은 충분한 휴식이 필요하며 다음 날 가벼운 활동은 가능한 경우가 많습니다. 몸 상태에 따라 1~2일 더 쉬는 것이 좋으며, 체육 활동이나 무거운 가방 드는 것은 1~2주간 피하는 것이 좋습니다.',
    aiSummary: '다음 날 학교는 가능하지만 체육 등 무리한 활동은 1~2주간 피해야 합니다.',
    tags: ['학교', '등교', '학생회복'],
    related: ['return-to-work', 'daily-life-recovery'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'alone-no-guardian',
    q: '보호자 없이 혼자 가면 수술을 안 해주나요?',
    a: '성인의 경우 본인 동의만으로 수술이 가능합니다. 다만 수면마취 후 귀가 안전을 위해 혼자 오시는 경우 대중교통 이용을 권장하며, 사전에 전화로 상황을 알려주시면 맞춤 안내를 드립니다.',
    aiSummary: '성인은 혼자 수술이 가능하며 수면마취 후 대중교통 이용을 권장합니다.',
    tags: ['보호자없음', '혼자수술', '성인'],
    related: ['alone-visit', 'companion-needed'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'alone-how-to-go-home',
    q: '수술 후 혼자 집에 어떻게 가요?',
    a: '수면마취 후에는 운전이 불가하므로 지하철·버스 등 대중교통을 이용하거나 택시를 이용하면 됩니다. 회복실에서 충분히 안정을 취한 후 보행이 가능한 상태가 되면 귀가하므로 큰 불편 없이 이동 가능합니다.',
    aiSummary: '수면마취 후 운전은 불가하며 대중교통이나 택시로 귀가하면 됩니다.',
    tags: ['혼자귀가', '대중교통', '택시'],
    related: ['driving-after-surgery', 'same-day-discharge'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'first-visit-what-to-bring',
    q: '처음 방문할 때 뭘 가져가야 해요?',
    a: '신분증(주민등록증·학생증·여권 등)을 지참하시면 됩니다. 수술 당일에는 금식이 필요하므로 사전에 금식 시간을 확인하고 편안한 복장으로 방문하시면 됩니다.',
    aiSummary: '신분증 지참 후 편안한 복장으로 방문하시면 됩니다. 수술 당일은 금식이 필요합니다.',
    tags: ['준비물', '첫방문', '신분증'],
    related: ['fasting-time', 'abortion-procedure-overview'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'waiting-room-privacy',
    q: '대기실에서 아는 사람 만날까봐 걱정돼요',
    a: '1인 상담실과 독립 동선으로 운영되어 다른 환자와 마주치는 상황을 최소화합니다. 걱정되신다면 예약 시 말씀해 주시면 대기 시간을 줄이는 방향으로 안내해 드립니다.',
    aiSummary: '독립 동선과 1인 상담실로 운영되어 다른 환자와 마주치는 상황을 최소화합니다.',
    tags: ['대기실', '프라이버시', '독립동선'],
    related: ['alone-visit', 'parents-privacy'],
    intent: 'privacy',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'first-time-gynecology',
    q: '산부인과 처음 가는데 너무 무서워요',
    a: '처음 방문이 두려운 마음은 매우 자연스럽습니다. 전화나 카카오톡으로 미리 궁금한 점을 물어보시면 방문 전 충분한 안내를 받을 수 있으며, 내원 시에도 친절하게 설명해 드립니다.',
    aiSummary: '처음 방문 전 전화나 카카오톡으로 미리 궁금한 점을 물어보실 수 있습니다.',
    tags: ['산부인과처음', '첫방문', '두려움'],
    related: ['kakao-consultation', 'scared-alone'],
    intent: 'mental-health',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'appointment-how',
    q: '예약은 어떻게 하나요?',
    a: '전화(02-585-3650) 또는 카카오톡 채널로 예약하실 수 있습니다. 예약 시 희망 날짜와 임신 주수를 말씀해 주시면 빠르게 일정을 잡아드립니다.',
    aiSummary: '전화 또는 카카오톡으로 예약 가능하며 임신 주수를 알려주시면 빠르게 일정을 잡아드립니다.',
    tags: ['예약방법', '전화예약', '카카오톡예약'],
    related: ['kakao-consultation', 'appointment-without-reservation'],
    intent: 'transactional',
    category: 'surgery',
    urgency: 'low',
    searchType: 'short',
    updatedAt: '2026-06-01',
  },
]
