import type { StandaloneFaq } from '../standaloneFaqs'

export const COST_FAQS: StandaloneFaq[] = [
  {
    slug: 'abortion-cost-6week',
    q: '6주 낙태수술 비용이 얼마예요?',
    a: '임신 6주 임신중절수술 비용은 45만원 내외로 초기일수록 비용이 낮습니다. 수술비·마취비·영양제가 포함된 최종 금액이며 카드·현금 동일가로 추가 비용이 없습니다.',
    aiSummary: '임신 6주 수술 비용은 45만원 내외이며 수술·마취·영양제 포함 금액입니다.',
    tags: ['6주비용', '낙태비용', '임신중절비용'],
    related: ['abortion-cost-8week', 'abortion-cost-by-week'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-cost-8week',
    q: '8주 낙태수술 비용 얼마예요?',
    a: '임신 8주 임신중절수술 비용은 60만원 내외입니다. 6주보다 주수가 높아지면서 수술 난이도가 올라가기 때문에 비용이 다소 증가하며, 빠른 결정일수록 비용과 위험도가 낮아집니다.',
    aiSummary: '임신 8주 수술 비용은 60만원 내외이며 주수가 높을수록 비용이 증가합니다.',
    tags: ['8주비용', '낙태비용', '임신중절비용'],
    related: ['abortion-cost-6week', 'abortion-cost-10week'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-cost-10week',
    q: '10주 임신중절수술 비용은요?',
    a: '임신 10주 임신중절수술 비용은 80만원 내외입니다. 10주부터는 자궁경부 확장이 필요해 시술 난이도가 높아지므로 초기보다 비용이 증가하며, 주수가 더 늘기 전에 빨리 결정하는 것이 좋습니다.',
    aiSummary: '임신 10주 수술 비용은 80만원 내외이며 자궁경부 확장이 필요해 비용이 높아집니다.',
    tags: ['10주비용', '낙태비용', '임신중절비용'],
    related: ['abortion-cost-8week', 'abortion-cost-by-week'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-cost-12week',
    q: '12주 중절수술 비용이 얼마나 돼요?',
    a: '임신 12주 임신중절수술 비용은 100만원 내외로 올라갑니다. 12주에 가까울수록 수술 복잡도와 회복 관리 범위가 커지므로 주수가 더 늘기 전에 빠른 상담을 권장합니다.',
    aiSummary: '임신 12주 수술 비용은 100만원 내외이며 빠른 결정이 비용 절감에 중요합니다.',
    tags: ['12주비용', '낙태비용', '임신중절비용'],
    related: ['abortion-cost-10week', 'abortion-weeks-limit'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'high',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-insurance-applicable',
    q: '임신중절수술 건강보험 적용 되나요?',
    a: '임신중절수술은 대부분 비급여 항목으로 건강보험 적용이 되지 않습니다. 단, 태아 기형이나 산모 생명 위협 등 의학적 사유가 있는 경우 일부 급여 적용이 가능하므로 상담 시 확인하는 것이 좋습니다.',
    aiSummary: '임신중절수술은 대부분 비급여이며 의학적 사유가 있을 때만 일부 보험 적용이 가능합니다.',
    tags: ['건강보험', '보험적용', '비급여'],
    related: ['abortion-cost-difference', 'health-insurance-record'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-cost-all-inclusive',
    q: '낙태수술 비용에 뭐가 다 포함돼요?',
    a: '수술비·수면마취비·사전 초음파 검사비·혈액검사비·영양제·부가세가 포함된 최종 금액으로 안내합니다. 카드·현금 동일가이며 상담 시 안내받은 금액 외 추가 비용이 발생하지 않습니다.',
    aiSummary: '수술·마취·초음파·혈액검사·영양제·부가세 포함 최종 금액이며 추가 비용이 없습니다.',
    tags: ['포함항목', '비용구성', '추가비용없음'],
    related: ['abortion-extra-cost', 'abortion-medication-cost'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-cost-installment',
    q: '임신중절수술 비용 할부도 되나요?',
    a: '카드 할부 결제가 가능한 경우가 있으므로 상담 시 결제 방법을 미리 문의하시면 됩니다. 비용 부담이 걱정되신다면 솔직하게 말씀해 주시면 가능한 방안을 안내해 드립니다.',
    aiSummary: '카드 할부 결제가 가능하며 상담 시 결제 방법을 미리 문의하면 됩니다.',
    tags: ['할부', '분할결제', '카드결제'],
    related: ['card-payment', 'abortion-cost-difference'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-cost-transparent',
    q: '비용이 투명하게 공개되는 병원인가요?',
    a: '네, 주수별 비용을 사전에 투명하게 안내드리며 상담 시 제시한 금액 외 추가 비용이 발생하지 않습니다. 수술 전 비용 전체를 확인하고 진행하기 때문에 예상치 못한 청구는 없습니다.',
    aiSummary: '주수별 비용을 투명하게 공개하며 상담 금액 외 추가 비용이 없습니다.',
    tags: ['투명비용', '비용공개', '추가비용없음'],
    related: ['abortion-cost-all-inclusive', 'abortion-cheap-hospital-safe'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-cost-phone-consult',
    q: '전화로 비용 문의하면 정확하게 알 수 있나요?',
    a: '전화 상담 시 임신 주수를 말씀해 주시면 정확한 비용을 바로 안내해 드립니다. 전화 상담은 무료이며 비밀이 완전히 보장됩니다.',
    aiSummary: '전화 상담 시 임신 주수를 말씀하시면 정확한 비용을 즉시 안내해 드립니다.',
    tags: ['전화상담', '비용문의', '무료상담'],
    related: ['kakao-consultation', 'abortion-consultation-fee'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-cost-compare',
    q: '다른 병원이랑 비교해서 비용이 적당한가요?',
    a: '비용만 단순 비교하기보다 수술 환경, 마취 안전성, 전문의 여부, 사후관리 포함 여부를 함께 확인하는 것이 중요합니다. 지나치게 저렴한 곳은 마취비·검사비를 별도 청구하거나 안전 시스템이 부족할 수 있습니다.',
    aiSummary: '비용 외에 마취 안전성과 전문의 여부를 함께 확인하는 것이 중요합니다.',
    tags: ['비용비교', '병원선택', '안전'],
    related: ['abortion-cheap-hospital-safe', 'abortion-hospital-selection'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-cost-sunday',
    q: '일요일 수술도 같은 비용인가요?',
    a: '일요일·공휴일 수술도 평일과 동일한 비용으로 진행됩니다. 주말에도 동일한 전문의가 수술하며 수술 비용에 차이가 없습니다.',
    aiSummary: '일요일·공휴일 수술도 평일과 동일한 비용으로 진행됩니다.',
    tags: ['일요일수술', '주말비용', '공휴일'],
    related: ['weekend-surgery', 'abortion-cost-all-inclusive'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'abortion-cost-early-vs-late',
    q: '일찍 수술받을수록 비용이 더 싼가요?',
    a: '네, 임신 주수가 낮을수록 수술 난이도가 낮아 비용이 줄어듭니다. 6주 미만 45만원대에서 시작해 주수가 올라갈수록 비용이 증가하므로 결정이 서면 빠를수록 경제적입니다.',
    aiSummary: '주수가 낮을수록 비용이 저렴합니다. 빠른 결정이 경제적·신체적으로 유리합니다.',
    tags: ['조기수술', '비용절감', '주수별비용'],
    related: ['abortion-cost-by-week', 'abortion-cost-6week'],
    intent: 'commercial',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
]
