import type { StandaloneFaq } from '../standaloneFaqs'

export const RECOVERY_FAQS: StandaloneFaq[] = [
  {
    slug: 'food-after-surgery',
    q: '수술 후 뭘 먹어야 좋아요?',
    a: '수술 당일은 죽이나 미음 같은 부드러운 음식부터 시작하고 다음 날부터 일반 식사가 가능합니다. 철분 보충을 위해 시금치·소고기·두부 등을 섭취하면 회복에 도움이 되며 음주는 최소 2주간 피해야 합니다.',
    aiSummary: '수술 당일은 죽으로 시작하고 철분 풍부한 음식을 섭취하면 회복에 도움됩니다.',
    tags: ['수술후음식', '식이요법', '회복'],
    related: ['alcohol-after-surgery', 'daily-life-recovery'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'work-next-day',
    q: '낙태 다음날 출근 가능해요?',
    a: '가벼운 사무직이라면 수술 다음 날 출근이 가능한 경우가 많습니다. 다만 수술 당일은 충분히 쉬는 것이 중요하며, 몸 상태에 따라 1~2일 더 쉬는 것이 회복에 유리합니다.',
    aiSummary: '가벼운 사무직은 다음 날 출근이 가능하지만 당일은 반드시 충분한 휴식이 필요합니다.',
    tags: ['다음날출근', '직장복귀', '회복'],
    related: ['return-to-work', 'daily-life-recovery'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'tampon-after-surgery',
    q: '수술 후 탐폰 써도 돼요?',
    a: '수술 후 최소 2주간은 탐폰 사용을 금지합니다. 자궁경부가 완전히 닫히기 전에 탐폰을 사용하면 감염 위험이 높아질 수 있으므로 반드시 생리대만 사용해야 합니다.',
    aiSummary: '수술 후 2주간 탐폰 사용은 감염 위험이 있어 금지이며 생리대만 사용해야 합니다.',
    tags: ['탐폰', '생리대', '감염예방'],
    related: ['shower-after-surgery', 'sex-after-surgery'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'brown-discharge-normal',
    q: '수술 후 갈색 분비물이 나오는데 정상인가요?',
    a: '수술 후 갈색 분비물은 오래된 혈액이 배출되는 것으로 정상적인 회복 과정입니다. 1~2주 정도 지속될 수 있으며 점차 줄어드는 것이 정상이지만 악취가 나거나 갑자기 양이 늘면 즉시 진료를 받아야 합니다.',
    aiSummary: '갈색 분비물은 정상 회복 과정이며 1~2주 내 점차 줄어듭니다.',
    tags: ['갈색분비물', '분비물', '회복'],
    related: ['abortion-bleeding-duration', 'fever-after-surgery'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'clot-after-surgery',
    q: '수술 후 덩어리가 나와요. 괜찮나요?',
    a: '500원짜리 동전보다 작은 혈덩어리는 정상 범위일 수 있습니다. 하지만 그보다 크거나 많은 양의 혈덩어리가 지속적으로 나온다면 불완전 유산 가능성이 있으므로 즉시 산부인과 진료를 받아야 합니다.',
    aiSummary: '작은 혈덩어리는 정상일 수 있지만 크거나 많으면 즉시 진료가 필요합니다.',
    tags: ['혈덩어리', '덩어리', '출혈'],
    related: ['abortion-bleeding-duration', 'fever-after-surgery'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'high',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'period-irregular-after',
    q: '수술 후 생리가 불규칙해졌어요',
    a: '수술 후 1~2번의 생리는 평소와 다르게 양이 많거나 적을 수 있고 주기가 불규칙할 수 있습니다. 이는 호르몬이 정상화되는 과정으로 2~3개월 내 회복되는 것이 일반적이며 3개월 이후에도 지속되면 상담이 필요합니다.',
    aiSummary: '수술 후 생리 불규칙은 호르몬 정상화 과정으로 2~3개월 내 회복됩니다.',
    tags: ['생리불규칙', '생리변화', '호르몬'],
    related: ['period-after-abortion', 'ovulation-after-surgery'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'smoking-after-surgery',
    q: '수술 후 담배 피워도 되나요?',
    a: '흡연은 혈액 순환을 방해하고 자궁 회복을 늦추므로 수술 후 최소 2주간 금연이 권장됩니다. 흡연은 감염 위험을 높이고 출혈 조절에도 부정적인 영향을 줄 수 있습니다.',
    aiSummary: '흡연은 자궁 회복을 방해하므로 수술 후 최소 2주간 금연이 권장됩니다.',
    tags: ['흡연', '금연', '회복'],
    related: ['alcohol-after-surgery', 'daily-life-recovery'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'antibiotic-must-take',
    q: '수술 후 항생제 꼭 먹어야 하나요?',
    a: '네, 수술 후 처방된 항생제는 감염 예방을 위해 반드시 정해진 기간 동안 빠짐없이 복용해야 합니다. 증상이 없어도 임의로 중단하면 감염 위험이 높아지고 항생제 내성이 생길 수 있습니다.',
    aiSummary: '항생제는 감염 예방을 위해 처방 기간 동안 반드시 빠짐없이 복용해야 합니다.',
    tags: ['항생제', '감염예방', '약복용'],
    related: ['fever-after-surgery', 'aftercare-checkup'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'high',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'hot-pack-after-surgery',
    q: '수술 후 핫팩이나 찜질하면 좋은가요?',
    a: '수술 직후에는 온열 찜질을 피하는 것이 좋습니다. 온열은 혈관을 확장시켜 출혈이 늘어날 수 있기 때문입니다. 통증이 심하면 진통제를 복용하고 의료진 지시에 따라 관리하는 것이 안전합니다.',
    aiSummary: '수술 직후 온열 찜질은 출혈을 늘릴 수 있어 피해야 하며 통증은 진통제로 관리합니다.',
    tags: ['찜질', '핫팩', '통증관리'],
    related: ['post-pain-normal', 'abortion-pain'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'sleep-position-after',
    q: '수술 후 어떤 자세로 자는 게 좋아요?',
    a: '특별히 제한된 자세는 없지만 편안한 자세로 충분히 쉬는 것이 가장 중요합니다. 복부에 압박을 주는 자세는 피하고 몸을 따뜻하게 유지하면서 충분한 수면을 취하는 것이 회복에 도움됩니다.',
    aiSummary: '특별히 제한된 자세는 없으며 편안하고 따뜻하게 충분한 수면을 취하는 것이 중요합니다.',
    tags: ['수면자세', '회복자세', '휴식'],
    related: ['daily-life-recovery', 'return-to-work'],
    intent: 'informational',
    category: 'surgery',
    urgency: 'low',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'when-to-go-er',
    q: '수술 후 응급실 가야 하는 상황은 언제예요?',
    a: '시간당 패드 2개 이상 교체가 필요한 과다출혈, 38도 이상 고열, 극심한 복통, 실신·어지러움이 심한 경우 즉시 응급실을 방문해야 합니다. 이런 증상은 감염이나 불완전 유산의 신호일 수 있습니다.',
    aiSummary: '과다출혈·고열·극심한 복통·실신이 있으면 즉시 응급실을 방문해야 합니다.',
    tags: ['응급실', '응급증상', '합병증'],
    related: ['fever-after-surgery', 'clot-after-surgery'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'high',
    searchType: 'ai-search',
    updatedAt: '2026-06-01',
  },
  {
    slug: 'pill-after-surgery',
    q: '수술 후 피임약 바로 시작해도 되나요?',
    a: '수술 당일부터 경구피임약 복용을 시작할 수 있으며 오히려 빠른 시작이 배란을 억제해 안전합니다. 피임 방법 선택은 상담 시 개인 상황에 맞게 안내받는 것이 좋습니다.',
    aiSummary: '경구피임약은 수술 당일부터 시작 가능하며 빠른 피임 시작이 안전합니다.',
    tags: ['피임약', '경구피임약', '피임'],
    related: ['contraception-after-surgery', 'ovulation-after-surgery'],
    intent: 'medical',
    category: 'surgery',
    urgency: 'medium',
    searchType: 'conversational',
    updatedAt: '2026-06-01',
  },
]
